### ISSUE TITLE
Data download gp tool

### ISSUE THREAD

**Issue by steveoh** [agrc/AddressPointEditor#103]
This appears to fail in production and have a different problem in the gcve migrated system.

**Comment by steveoh** [comment]
> SGID10.sde\SGID10.BOUNDARIES.Counties does not exist or is not supported 

This showed up in the logs.

**Comment by nathankota** [comment]
addressediting.utah.gov
- Select `UTM Zone 12 North`, `Shapefile`, `Cache`
- Result is:

![image](https://user-images.githubusercontent.com/15659642/162775957-bcfa430b-49a7-4096-b7bf-45f75621aa8d.png)

**Comment by mheagin** [comment]
Ok sorry  I panicked when I saw my data missing and did not look at the details.
