### ISSUE TITLE
Identify the Road Attributes

### ISSUE THREAD

**Issue by mheagin** [agrc/AddressPointEditor#89]
Is it possible to do an Identify on the Roads layer? A few users need to add address and are unsure of how to structure the address, and viewing the roads attributes would help.
A simple list using these attributes would work:
FULLNAME
L_F_ADD
L_T_ADD
R_F_ADD
R_T_ADD
PREDIR
SUFDIR
ALIAS1
ALIAS1TYP
ALIAS2
ALIAS2TYP
ACSALIAS
HWYNAME
Thanks

**Comment by stdavis** [comment]
Yes, this would be doable.

On Fri, Jan 23, 2015 at 4:19 PM, Mike Heagin <notifications@github.com>
wrote:

> Is it possible to do an Identify on the Roads layer? A few users need to
> add address and are unsure of how to structure the address, and viewing the
> roads attributes would help.
> A simple list using these attributes would work:
> FULLNAME
> L_F_ADD
> L_T_ADD
> R_F_ADD
> R_T_ADD
> PREDIR
> SUFDIR
> ALIAS1
> ALIAS1TYP
> ALIAS2
> ALIAS2TYP
> ACSALIAS
> HWYNAME
> Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/agrc/AddressPointEditor/issues/89>.
>



-- 
*Scott Davis*
Utah AGRC <http://gis.utah.gov/developer/>
stdavis@utah.gov
@ScottAGRC <https://twitter.com/ScottAGRC>

**Comment by mheagin** [comment]
One more field Kelly thought we could use also is the ADDR_SYS, help them
know their areas when it close to city limits.
Thanks

On Mon, Jan 26, 2015 at 1:16 PM, Scott Davis <notifications@github.com>
wrote:

> Yes, this would be doable.
>
> On Fri, Jan 23, 2015 at 4:19 PM, Mike Heagin <notifications@github.com>
> wrote:
>
> > Is it possible to do an Identify on the Roads layer? A few users need to
> > add address and are unsure of how to structure the address, and viewing
> the
> > roads attributes would help.
> > A simple list using these attributes would work:
> > FULLNAME
> > L_F_ADD
> > L_T_ADD
> > R_F_ADD
> > R_T_ADD
> > PREDIR
> > SUFDIR
> > ALIAS1
> > ALIAS1TYP
> > ALIAS2
> > ALIAS2TYP
> > ACSALIAS
> > HWYNAME
> > Thanks
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/agrc/AddressPointEditor/issues/89>.
> >
>
>
>
> --
> *Scott Davis*
> Utah AGRC <http://gis.utah.gov/developer/>
> stdavis@utah.gov
> @ScottAGRC <https://twitter.com/ScottAGRC>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/agrc/AddressPointEditor/issues/89#issuecomment-71529812>
> .
>



-- 
Mike Heagin
AGRC
gis.utah.gov
801-537-9296

**Comment by brigsz** [comment]
I am going to take the liberty to close this one.  it is from 2015

**Comment by brigsz** [comment]
Good riddance
