### ISSUE TITLE
Show parcel lines on Hybrid

### ISSUE THREAD

**Issue by stdavis** [agrc/AddressPointEditor#90]
@gregbunce passed on a request from Garfield county to allow them to see parcel lines on top of the Hybrid base map. I think that we could just add the parcel lines as a overlay (possibly linked with Hybrid?) to the layer selector.

**Comment by steveoh** [comment]
Yeah adding it as an overlay layer is a great idea!

**Comment by stdavis** [comment]
Ran into [this issue](https://gisdevs.slack.com/archives/arcgis-web/p1472216522000906) when I tried to add the parcel vector tiles layer to layer selector.

**Comment by stdavis** [comment]
Looks like [this is a bug that's fixed in 3.18](https://gisdevs.slack.com/archives/arcgis-web/p1472224728000919). Confirmed that it doesn't work in 3.17, 3.16 & 3.15. So we will have to wait until 3.18 is released.

**Comment by stdavis** [comment]
@gregbunce: This was pushed to production today.
