### ISSUE TITLE
Add Notes and StreetAlias fields to editor app

### ISSUE THREAD

**Issue by ZachBeck** [agrc/AddressPointEditor#91]

**Comment by steveoh** [comment]
this is the logged out view
![image](https://cloud.githubusercontent.com/assets/325813/18318085/76b5dc44-74dd-11e6-8451-610cdfac5922.png)

and logged in view
![image](https://cloud.githubusercontent.com/assets/325813/18318406/d2e0f3e0-74de-11e6-8c96-57260ac1f494.png)
